name: Digger Dev

on:
  pull_request:
    branches: [ "master" ]
    types: [ opened, synchronize ]
  issue_comment:
    types: [created]
  workflow_dispatch:


jobs:
  plan:
    runs-on: ubuntu-latest
    environment: production
    permissions:    
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status

    steps:
      - uses: actions/checkout@v4
      - name: digger run
        uses: diggerhq/digger@v0.3.1
        with:
          digger-organisation: digger-playground
          digger-token: ${{ secrets.DIGGER_TOKEN }}
          digger-hostname: https://cloud.digger.dev
          digger-filename: digger_dev.yml
          setup-aws: true
          disable-locking: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV_NAME: dev